config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :quotations
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :institutions
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  root 'quotations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/institution.rb
class Institution < ApplicationRecord
	has_many :clients, dependent: :destroy
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:rut, :dv, :business_name)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<div class= "well bs-component">
<%= form_with(model: institution, local: true) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :rut , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.number_field :rut, id: :institution_rut , class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :dv , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_field :dv, id: :institution_dv , class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :business_name , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_field :business_name, id: :institution_business_name , class: "form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>
</div>

app/views/institutions/edit.html.erb
<h1>Editing Institution</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Mostrar', @institution %> |
<%= link_to 'Volver', institutions_path %>

app/views/institutions/index.html.erb
<h1>Instituciones</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre Institución</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= number_to_currency(institution.rut, {:precision => 0, :unit => "",:delimiter => "."}) %>-<%= institution.dv %></td>
        <td><%= institution.business_name %></td>
        <td><button type="button" class="btn btn-success"><%= link_to 'Mostrar', institution %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Editar', edit_institution_path(institution) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Eliminar', institution, method: :delete, data: { confirm: 'Está seguro(a) que quiere eliminarlo?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Nueva Institución', new_institution_path %>

app/views/institutions/new.html.erb
<h1>Nueva Institución</h1>

<%= render 'form', institution: @institution %>

<%= link_to 'Volver', institutions_path %>

app/views/institutions/show.html.erb
<div class="table-responsive">
<table class="table table-striped">
  <thead>
  	<tr>
  		<th>Rut</th>
  		<th>Institución</th>
  	</tr>
  </thead>
  <tbody>
  	<tr>
  		 <td><%= number_to_currency(@institution.rut, {:precision => 0, :unit => "",:delimiter => "."}) %>-<%= @institution.dv %></td>
  		<td><%= @institution.business_name %></td>
  	</tr>
  </tbody>
 </table>
 </div>

<%= link_to 'Editar', edit_institution_path(@institution) %> |
<%= link_to 'Volver', institutions_path %>