config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :quotations
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :institutions
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  root 'quotations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :state
  belongs_to :client
  belongs_to :user
  mount_uploader :document, DocumentUploader

  def self.created_last_week
    group_by_week(:created_at, last: 8).count
  end

  def self.group_by_state	
     quotation.group(:state).count
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < InheritedResources::Base
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @quotations = current_user.quotations
    @states = State.all
    @clients = current_user.clients
    @user = current_user
  end

  def show
  end

  def new
    @quotation = Quotation.new
    @states = State.all 
    @clients = current_user.clients
    @user = current_user
  end

   def edit
    @states = State.all
    @clients = current_user.clients
    @user = current_user
  end



 def create
  @states = State.all
  @quotation = Quotation.new(quotation_params)
  @quotation.date_create = Time.now
  @quotation.user = current_user
#  @quotation.client = current_user.clients

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    @states = State.all  
    @quotation.user = current_user
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    def set_quotation
      @quotation = Quotation.find(params[:id])  
    end
    
    def quotation_params
      params.require(:quotation).permit(:code_quotation, :title, :description, :state_id, :user_id, :client_id, :document, :date_create)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<div class= "well bs-component">
<%= form_with(model: quotation, local: true) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :Código, class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_field :code_quotation, id: :quotation_code_quotation %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Título, class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_field :title, id: :quotation_title %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Descripción, class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_area :description, id: :quotation_description %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Estado , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.select :state_id, options_for_select(@states.map {|state| [state.name, state.id]}, form.object.state_id), {}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Cliente , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.select :client_id, options_for_select(@clients.map {|client| [client.fullname, client.id]}, form.object.client_id), {}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Documento, class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.file_field :document, id: :document%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div>


<% end %>
</div>

app/views/quotations/edit.html.erb
<h1>Editar Cotización</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Mostrar', @quotation %> |
<%= link_to 'Volver', quotations_path %>

app/views/quotations/index.html.erb
<h1>Cotizaciones</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Título</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Cliente</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quotations.each do |quotation| %>
      <tr>
        <td><%= quotation.code_quotation.to_s  %></td>
        <td><%= quotation.title %></td>
        <td><%= quotation.description %></td>
        <td><%= quotation.state.name %></td>
        <td><%= quotation.client.fullname%></td>
        <td><button type="button" class="btn btn-success"><%= link_to 'Mostrar', quotation %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Editar', edit_quotation_path(quotation) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Eliminar', quotation, method: :delete, data: { confirm: 'Está seguro(a) que quiere eliminarlo?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Nueva Cotización', new_quotation_path %>

app/views/quotations/new.html.erb
<h1>Nueva Cotización</h1>

<%= render 'form', quotation: @quotation %>

<%= link_to 'Volver', quotations_path %>

app/views/quotations/show.html.erb
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Cliente</th>
      <th>Documento</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @quotation.code_quotation %></td>
      <td><%= @quotation.title %></td>
      <td><%= @quotation.state.name %></td>
      <td><%= @quotation.client.fullname %></td>
      <td><A HREF="<%= @quotation.document%>">Mostrar</A></td>

    </tr>
  </tbody>
 </table>
 </div>

<%= link_to "Pagos", payments_path %> |
<%= link_to 'Editar', edit_quotation_path(@quotation) %> |
<%= link_to 'Volver', quotations_path %>