config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :quotations
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :institutions
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  root 'quotations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :quotation
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    #@payments = Payment.all
    #@payments = Payment.first
    @quotations = current_user.quotations
    @payments = Payment.where(quotation_id: @quotations.ids)

    #@payments = Payment.joins("INNER JOIN quotations ON posts.author_id = authors.id AND posts.published = 't'")

#Author.joins("INNER JOIN posts ON posts.author_id = authors.id AND posts.published = 't'")
    #@payments = Payment.find(params[:payment])
    #@payment = Payment.find(params[:quotation_id])    
    #@payments = current_user.payments
   

  end

  def show
  end

  def new
    @payment = Payment.new
    @quotations = current_user.quotations
  end


  private
    def set_payment
      @payment = Payment.find(params[:id])  
    end

    def payment_params
      params.require(:payment).permit(:OC, :coin, :rode, :iva, :quotation_id)
    end

    def set_quotation
      @quotation = Quotation.find(params[:id])  
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class= "well bs-component">
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :OC, class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.text_field :OC, id: :payment_OC %>
    </div>
  </div>


    <div class="form-group">
      <%= form.label :Moneda, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= form.text_field :coin, id: :payment_coin %>
      </div>
    </div>

  <div class="form-group">
    <%= form.label :Monto, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= form.text_field :rode, id: :payment_rode %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :Iva, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= form.check_box :iva, id: :payment_iva %>
    </div>
  </div>


  <div class="form-group">
    <%= form.label :Cotización , class: "col-lg-2 control-label"%>
    <div class="col-lg-10">
      <%= form.select :quotation_id, options_for_select(@quotations.map {|quotation| [quotation.description, quotation.id]}, form.object.quotation_id), {}, {class: "form-control"} %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div>


<% end %>
</div>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagos</h1>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Oc</th>
      <th>Moneda</th>
      <th>Monto</th>
      <th>Iva</th>
      <th>Cotización</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.OC %></td>
        <td><%= payment.coin %></td>
        <td><%= payment.rode %></td>
        <td><%= payment.iva %></td>
        <td><%= payment.quotation.code_quotation %></td>
        <td><button type="button" class="btn btn-success"><%= link_to 'Mostrar', payment %></button>
        <button type="button" class="btn btn-warning"><%= link_to 'Editar', edit_payment_path(payment) %></button>
        <button type="button" class="btn btn-danger"><%= link_to 'Eliminar', payment, method: :delete, data: { confirm: 'Está seguro(a) que quiere eliminarlo?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

<%= link_to 'Nuevo Pago', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oc:</strong>
  <%= @payment.OC %>
</p>

<p>
  <strong>Coin:</strong>
  <%= @payment.coin %>
</p>

<p>
  <strong>Rode:</strong>
  <%= @payment.rode %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @payment.iva %>
</p>

<p>
  <strong>Quotation:</strong>
  <%= @payment.quotation %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>