config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :quotations
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clients
  resources :institutions
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  root 'quotations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :institution
  has_many :user_clients, dependent: :destroy
  has_many :users,through: :user_clients, dependent: :destroy


  def fullname
    "#{name} #{last_name}"
  end

end

app/models/institution.rb
class Institution < ApplicationRecord
	has_many :clients, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :quotation
end

app/models/payments_detail.rb
class PaymentsDetail < ApplicationRecord
  belongs_to :payments
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :state
  belongs_to :client
  belongs_to :user
  mount_uploader :document, DocumentUploader

  def self.created_last_week
    group_by_week(:created_at, last: 8).count
  end

  def self.group_by_state	
     quotation.group(:state).count
  end
end

app/models/quote_detail.rb
class QuoteDetail < ApplicationRecord
  belongs_to :quotation
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_clients, dependent: :destroy
  has_many :clients,through: :user_clients, dependent: :destroy
  has_many :quotations, dependent: :destroy
end

app/models/user_client.rb
class UserClient < ApplicationRecord
  belongs_to :user
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /clients
  # GET /clients.json
  def index
    @clients = current_user.clients
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @institutions = Institution.all
  end

  # GET /clients/1/edit
  def edit
    @institutions = Institution.all
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        @user_client = UserClient.new
        @user_client.user = current_user
        @user_client.client = @client
        @user_client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:rut, :dv, :name, :last_name, :institution_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < InheritedResources::Base
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    #@payments = Payment.all
    #@payments = Payment.first
    @quotations = current_user.quotations
    @payments = Payment.where(quotation_id: @quotations.ids)

    #@payments = Payment.joins("INNER JOIN quotations ON posts.author_id = authors.id AND posts.published = 't'")

#Author.joins("INNER JOIN posts ON posts.author_id = authors.id AND posts.published = 't'")
    #@payments = Payment.find(params[:payment])
    #@payment = Payment.find(params[:quotation_id])    
    #@payments = current_user.payments
   

  end

  def show
  end

  def new
    @payment = Payment.new
    @quotations = current_user.quotations
  end


  private
    def set_payment
      @payment = Payment.find(params[:id])  
    end

    def payment_params
      params.require(:payment).permit(:OC, :coin, :rode, :iva, :quotation_id)
    end

    def set_quotation
      @quotation = Quotation.find(params[:id])  
    end
end

app/controllers/quotations_controller.rb
class QuotationsController < InheritedResources::Base
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @quotations = current_user.quotations
    @states = State.all
    @clients = current_user.clients
    @user = current_user
  end

  def show
  end

  def new
    @quotation = Quotation.new
    @states = State.all 
    @clients = current_user.clients
    @user = current_user
  end

   def edit
    @states = State.all
    @clients = current_user.clients
    @user = current_user
  end



 def create
  @states = State.all
  @quotation = Quotation.new(quotation_params)
  @quotation.date_create = Time.now
  @quotation.user = current_user
#  @quotation.client = current_user.clients

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    @states = State.all  
    @quotation.user = current_user
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    def set_quotation
      @quotation = Quotation.find(params[:id])  
    end
    
    def quotation_params
      params.require(:quotation).permit(:code_quotation, :title, :description, :state_id, :user_id, :client_id, :document, :date_create)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Sigcot</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><%= link_to "Clientes", clients_path %></li>
      <li><%= link_to "Instituciones", institutions_path %></li>
      <li><%= link_to "Cotizaciones", quotations_path %></li> 
    </ul>
    <ul class="nav navbar-nav navbar-right">
    	<li>
    	<% if current_user %>
      		<a href="javascript:void(0)">Bienvenid@ <%= current_user.nombre %></a>
      	<% else %>
      		<%= link_to  new_user_registration_path do %>
      			<span class="glyphicon glyphicon-user"></span>
      			Sign Up
      		<% end %>
      	<% end %>
      	</li>
      	<li>
      	<% if current_user %>
    		<%= link_to destroy_user_session_path, method: :delete do %>
    			<span class="glyphicon glyphicon-log-out"></span>
    			Logout
    		<% end %>
		<% else %>
    		<%= link_to  new_user_session_path do %>
    			<span class="glyphicon glyphicon-log-in"></span>
    			Login
    		<% end %>

		<% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cotizaciones</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <br>  
      <% if notice || alert %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_chart.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% my_chart = Quotation.created_last_week %>

<%= bar_chart my_chart %>